### ISSUE TITLE
Build is producing a false positive

### ISSUE THREAD

**Issue by willedwards** [CJSCommonPlatform/microservice_framework#132]
I observed CakeShopIT.java fails the build, but appears to be ignored. See line 11425 in travis CI build log (below)

17:28:16,501 WARN  [OnePool] IJ000621: Destroying connection that could not be validated: null

17:28:16,507 WARN  [SqlExceptionHelper] SQL Error: 42102, SQLState: 42S02

17:28:16,508 ERROR [SqlExceptionHelper] Table "RECIPE" not found; SQL statement:

select count(recipe0_.id) as col_0_0_ from recipe recipe0_ where recipe0_.id=? [42102-173]

**Comment by purple52** [comment]
This is a misleading error - it comes from a test that is checking transaction rollback behaviour. We remove the database during the test and check how the transaction is handled. Ideally, we would squash the error messages so that the logs are clean and not confusing, but we haven't had time to investigate the best way to do this.
