### ISSUE TITLE
Message numbering

### ISSUE THREAD

**Issue by gogit** [CJSCommonPlatform/microservice_framework#233]
Add a unique message number (sequence_id from event_log ??) to the Metadata.  The pros of adding an unique message number are

- Identifying lost messages ( for whatever reason) and audit

- Processing messages in order

- Avoid processing duplicates

- IVs (for encryption) can use this information

**Comment by purple52** [comment]
We have one already - every message has a UUID called "id" in the metadata.

**Comment by gogit** [comment]
The id will not give the order of messages.

**Comment by purple52** [comment]
The order of messages only has meaning in the context of events in a stream. In this case, the order of events is indicated by the streamId and version fields. Commands and queries are received and processed in parallel, and as such ordering has no meaning.

**Comment by gogit** [comment]
A contrived example
 
  Update first name to Jo
  Stream id: 2345
  Version  : 1

  Update first name to Joey
  Stream id: 2345
  Version  : 1

If you received 2 messages like the above, they would enter the event_log table
(in sequence [sequence_id]) and the ( global context message number (copied from sequence_id) )
would help resolve the order.

**Comment by purple52** [comment]
They wouldn't make it into the event store like that. The event store enforces a strict ordering of events within a stream because it has to; streamId and version will always be unique. A stream is a sequence of state changes to a part of the domain that has a clearly defined transactional boundary.

If two commands processed in parallel try to append events to the same version of a stream, the second will fail. There are various ways to deal with this, but we don't have a system-wide concept of which command is 1st or 2nd because it doesn't mean anything - their ordering is arbitrary until they are processed and events are raised as a consequence.
