### ISSUE TITLE
pom error

### ISSUE THREAD

**Issue by vembusridhar** [CJSCommonPlatform/microservice_framework#454]
getting the below error while trying to do a complie after doing a git pull:

[ERROR]     Non-resolvable parent POM for uk.gov.justice.services:microservice-framework:1.6.0: Failure to find uk.gov.justice:maven-framework-parent-pom:pom:1.2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 7, column 13 -> [Help 2]

**Comment by purple52** [comment]
Which branch are you trying to build? 1.6.0 is a release version, and should be available for download direct from Bintray. Master is on 3.0.0-SNAPSHOT.

**Comment by vembusridhar** [comment]
It was from Master, but I pulled it from 1.6.0 and even few other release
branches, but I'm getting the same error. Not sure if I am doing something
wrong?

**Comment by purple52** [comment]
The error you posted above looks like it is from trying to build from the 1.6.0 release tag.

The problem is that we do not push any of our artifacts to Maven Central, so you cannot build the project yourself without adding our Maven repo unless you build all our dependencies locally in the correct order (which is time consuming, but there is a script in the framework project to do that).

We recently switched to uploading release versions to Bintray. You will need to tell Maven to use that repository in order to build any of our projects. See https://github.com/CJSCommonPlatform/travis-settings/blob/master/settings.xml for an example of adding our Bintray repo to settings.xml alongside Maven central.
